
server {
    listen 80;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 5s;
    proxy_read_timeout 15s;

    location = /saude {
        default_type application/json;
        return 200 '{"status":"ok","servico":"gateway"}';
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /usuarios    { proxy_pass http://usuarios:8000; }
    location = /login     { proxy_pass http://usuarios:8000; }
    location ~ ^/livros/[0-9]+/(reservar|liberar)$ {
        default_type application/json;
        return 403 '{"detail":"Rota interna"}';
    }

    location /livros      { proxy_pass http://livros:8000; }
    location /emprestimos { proxy_pass http://emprestimos:8000; }

    location /notificacoes {
        limit_except GET { deny all; }
        proxy_pass http://notificacoes:8000;
    }
}
