global:
  scrape_interval: 15s

scrape_configs:
  - job_name: usuarios
    static_configs:
      - targets: ["usuarios:8000"]
  - job_name: livros
    static_configs:
      - targets: ["livros:8000"]
  - job_name: emprestimos
    static_configs:
      - targets: ["emprestimos:8000"]
  - job_name: notificacoes
    static_configs:
      - targets: ["notificacoes:8000"]
